# 도커 이미지의 기반 이미지 설정
FROM node:14-alpine

# 앱 소스코드를 저장할 디렉토리 생성
WORKDIR /app

# 앱 의존성 설치
COPY ./frontend .

# `/app/node_modules/.bin`을 $PATH 에 추가
ENV PATH /app/node_modules/.bin:$PATH

RUN npm install --no-cache
RUN npm install -g react-scripts
RUN npm install -g react-router-dom
RUN apk add --no-cache git

# 앱 빌드
RUN npm run build

EXPOSE 3000
# 앱 실행을 위한 명령어 설정
CMD ["npm", "start"]
