# Generated by Django 4.2.4 on 2023-12-10 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='town/')),
                ('area_welfare', models.FloatField(default=0, null=True)),
                ('town_welfare', models.FloatField(default=0, null=True)),
                ('town_culture', models.FloatField(default=0, null=True)),
                ('town_facility', models.FloatField(default=0, null=True)),
                ('town_citizen', models.FloatField(default=0, null=True)),
                ('advantage', models.TextField(null=True)),
                ('disadvantage', models.TextField(null=True)),
                ('star', models.FloatField(default=0, null=True)),
                ('update_at', models.DateTimeField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.area')),
            ],
            options={
                'db_table': 'Town',
            },
        ),
        migrations.CreateModel(
            name='Town_Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('area_welfare', models.FloatField(null=True)),
                ('town_welfare', models.FloatField(null=True)),
                ('town_culture', models.FloatField(null=True)),
                ('town_facility', models.FloatField(null=True)),
                ('town_citizen', models.FloatField(null=True)),
                ('advantage', models.TextField(null=True)),
                ('disadvantage', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='town.town')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Town_Review',
            },
        ),
    ]
