# Generated by Django 4.2.4 on 2023-08-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0004_alter_town_area_welfare_alter_town_town_citizen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='star',
            field=models.FloatField(default=0, null=True),
        ),
    ]
