# Generated by Django 4.2.4 on 2023-08-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0007_alter_town_area_welfare_alter_town_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='advantage',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='disadvantage',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='town_review',
            name='advantage',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='town_review',
            name='disadvantage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='town_review',
            name='area_welfare',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='town_review',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='town_review',
            name='star',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='town_review',
            name='town_citizen',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='town_review',
            name='town_culture',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='town_review',
            name='town_facility',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='town_review',
            name='town_welfare',
            field=models.FloatField(null=True),
        ),
    ]
