# Generated by Django 4.2.4 on 2023-08-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0008_town_advantage_town_disadvantage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town_review',
            name='star',
        ),
    ]
