# Generated by Django 4.2.4 on 2023-08-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0009_remove_town_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
