# Generated by Django 4.2.4 on 2023-08-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_area_name_remove_area_state_area_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(db_column='city', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(db_column='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.job'),
        ),
    ]
