# Generated by Django 4.2.4 on 2023-08-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_area_name_remove_area_state_area_city_and_more'),
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_review',
            name='star',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='funding_rate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product_review',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
