# Generated by Django 4.2.4 on 2023-08-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='한 박스', max_length=200, null=True),
        ),
    ]
