# Generated by Django 4.2.4 on 2023-08-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_remove_product_weight_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200, null=True)),
                ('details', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.category'),
        ),
    ]
