# Generated by Django 4.2.4 on 2023-08-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0005_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='period',
        ),
    ]
