# Generated by Django 4.2.4 on 2023-08-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_remove_product_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='period',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
