# Generated by Django 4.2.4 on 2023-08-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_product_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_description',
            field=models.TextField(null=True),
        ),
    ]
