# Generated by Django 4.2.4 on 2023-08-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_farmer_inquery_user_alter_normal_inquery_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='partner',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
