# Generated by Django 4.2.4 on 2023-08-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_remove_farmer_inquery_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
